M48
; DRILL file {KiCad 9.0.7-9.0.7~ubuntu24.04.1} date 2026-01-13T19:14:42-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-01-13T19:14:42-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7-9.0.7~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1000
%
G90
G05
T1
X6.9685Y-3.8862
X6.9685Y-4.6862
M30
